In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [2]:
from sklearn.datasets import load_digits

In [3]:
digits = load_digits()

In [4]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2, random_state=42)

In [16]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
lr.score(X_test,y_test)

0.975

In [17]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9861111111111112

In [18]:
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9805555555555555

In [19]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [23]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [24]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [25]:
get_score(lr, X_train, X_test, y_train, y_test)

0.975

In [26]:
get_score(svm, X_train, X_test, y_train, y_test)

0.9861111111111112

In [27]:
from sklearn.model_selection import StratifiedGroupKFold
folds = StratifiedGroupKFold(n_splits=3)

In [38]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(lr, X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [39]:
scores_lr

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [32]:
scores_rf

[0.9348914858096828, 0.9549248747913188, 0.9215358931552587]

In [33]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [40]:
from sklearn.model_selection import cross_val_score
cross_val_score(lr, digits.data, digits.target, cv=3)

array([0.91986644, 0.94323873, 0.91652755])

In [41]:
cross_val_score(svm, digits.data, digits.target, cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [42]:
cross_val_score(rf, digits.data, digits.target, cv=3)

array([0.93823038, 0.95492487, 0.91819699])