In [3]:
import pandas as pd
import numpy as np

In [4]:
from sklearn.datasets import load_iris
iris = load_iris()

In [5]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [6]:
df = pd.DataFrame(iris.data, columns= iris.feature_names)
df['flower'] = iris.target
df['flower_name'] = df['flower'].apply(lambda x: iris.target_names[x])
df[35:45]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
35                5.0               3.2                1.2               0.2   
36                5.5               3.5                1.3               0.2   
37                4.9               3.6                1.4               0.1   
38                4.4               3.0                1.3               0.2   
39                5.1               3.4                1.5               0.2   
40                5.0               3.5                1.3               0.3   
41                4.5               2.3                1.3               0.3   
42                4.4               3.2                1.3               0.2   
43                5.0               3.5                1.6               0.6   
44                5.1               3.8                1.9               0.4   

    flower flower_name  
35       0      setosa  
36       0      setosa  
37       0      setosa  
38       0      setosa  
39       0      setosa  
40       0      setosa  
41       0      setosa  
42       0      setosa  
43       0      setosa  
44       0      setosa

In [7]:
X = df.drop(['flower','flower_name'],axis=1)
y = df['flower']

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
from sklearn.svm import SVC
sv = SVC(kernel='rbf',gamma='auto',C=30)
sv.fit(X_train, y_train)
sv.score(X_test, y_test)

1.0

In [10]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel='linear',C=10,gamma='auto'),X,y,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [11]:
cross_val_score(SVC(kernel='rbf',C=10,gamma='auto'),X,y,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [12]:
cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),X,y,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [13]:
kernels = ['rbf','linear']
C = [1,10,20,30]
avg_scores = {}
for kvals in kernels:
    for cvals in C:
        cv_score = cross_val_score(SVC(kernel=kvals,C=cvals,gamma='auto'),X,y,cv=5)
        avg_scores[kvals + '_' + str(cvals)] = np.average(cv_score)
avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'rbf_30': 0.96,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'linear_30': 0.96}

In [14]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(SVC(gamma='auto'),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear'] 
},cv=5, return_train_score=False)

clf.fit(X, y)
clf.cv_results_

{'mean_fit_time': array([0.00272889, 0.00385213, 0.00319371, 0.00333934, 0.00013485,
        0.00340409, 0.00099778, 0.00220346]),
 'std_fit_time': array([0.00395569, 0.00634406, 0.00638742, 0.00667868, 0.0002697 ,
        0.00680819, 0.00163419, 0.00440693]),
 'mean_score_time': array([0.        , 0.00240269, 0.00012918, 0.        , 0.00302696,
        0.        , 0.        , 0.00025811]),
 'std_score_time': array([0.        , 0.00480537, 0.00025835, 0.        , 0.00605392,
        0.        , 0.        , 0.00051622]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'ke

In [15]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.002729      0.003956         0.000000        0.000000        1   
1       0.003852      0.006344         0.002403        0.004805        1   
2       0.003194      0.006387         0.000129        0.000258       10   
3       0.003339      0.006679         0.000000        0.000000       10   
4       0.000135      0.000270         0.003027        0.006054       20   
5       0.003404      0.006808         0.000000        0.000000       20   
6       0.000998      0.001634         0.000000        0.000000       30   
7       0.002203      0.004407         0.000258        0.000516       30   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
6          rbf     {'C': 30, 'kernel': 'rbf'}           0.966667   
7       linear  {'C': 30, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   
6                1.0           0.900000           0.933333                1.0   
7                1.0           0.900000           0.900000                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6  
6         0.960000        0.038873                7  
7         0.960000        0.048990                7

In [16]:
clf.best_score_

0.9800000000000001

In [17]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [18]:
from sklearn.model_selection import RandomizedSearchCV

clf1 = RandomizedSearchCV(SVC(gamma='auto'),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear'] 
},cv=5, return_train_score=False,n_iter=2)

clf1.fit(X, y)
pd.DataFrame(clf1.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1       10       linear         0.973333

In [19]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [20]:
model_params = {
    'svm': {
        'model':SVC(gamma='auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['rbf','linear']
        }
    },
    'random_forest': {
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10]
        }
    },
    'logistic_regression': {
        'model':LogisticRegression(solver='liblinear'),
        'params':{
            'C':[1,5,10]
        }
    }
}

In [21]:
from sklearn.model_selection import GridSearchCV
scores = []

for model_name,mp in model_params.items():
    clf = GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(X, y)
    scores.append({
        'model' : model_name,
        'best_score' : clf.best_score_,
        'best_params' : clf.best_params_
    })

df = pd.DataFrame(scores, columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}

In [22]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB

In [23]:
from sklearn.datasets import load_digits
digits_data = load_digits()

In [24]:
dir(digits_data)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [25]:
df = pd.DataFrame(digits_data.data, columns=digits_data.feature_names)
df['target'] = digits_data.target
df

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0           0.0        0.0        0.0        0.0  ...        0.0        0.0   
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
2           0.0        0.0        0.0        0.0  ...        0.0        0.0   
3           0.0        0.0        0.0        8.0  ...        0.0        0.0   
4           0.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1792        0.0        0.0        0.0        1.0  ...        0.0        0.0   
1793        1.0        0.0        0.0        0.0  ...        0.0        0.0   
1794        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1796        0.0        0.0        0.0        2.0  ...        0.0        0.0   

      pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0           0.0        6.0       13.0       10.0        0.0        0.0   
1           0.0        0.0       11.0       16.0       10.0        0.0   
2           0.0        0.0        3.0       11.0       16.0        9.0   
3           0.0        7.0       13.0       13.0        9.0        0.0   
4           0.0        0.0        2.0       16.0        4.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        2.0       14.0       15.0        9.0        0.0   
1793        0.0        6.0       16.0       14.0        6.0        0.0   
1794        0.0        2.0        9.0       13.0        6.0        0.0   
1795        0.0        5.0       12.0       16.0       12.0        0.0   
1796        1.0        8.0       12.0       14.0       12.0        1.0   

      pixel_7_7  target  
0           0.0       0  
1           0.0       1  
2           0.0       2  
3           0.0       3  
4           0.0       4  
...         ...     ...  
1792        0.0       9  
1793        0.0       0  
1794        0.0       8  
1795        0.0       9  
1796        0.0       8  

[1797 rows x 65 columns]

In [26]:
X = df.drop('target', axis=1)
y = df['target']

In [27]:
models = {
    'SVM':{
        'model': SVC(),
        'params':{
            'C':[1,10,20,30],
            'kernel':['poly','sigmoid','rbf','linear']
        }
    },
    'Random Forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators': [10,50,100,500],
            'criterion': ['gini','entropy','log_loss']
        }
    },
    'Logistic Regression':{
        'model':LogisticRegression(max_iter=2000),
        'params':{
            'C':[1,10,20,30],
            'solver': ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
        }
    },
    'Gaussian':{
        'model':GaussianNB(),
        'params':{}
    },
    'Multinomial':{
        'model':MultinomialNB(alpha=1),
        'params':{
            'fit_prior':[True,False]
        }
    },
    'decision_tree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini','entropy'],
            
        }
    }
    
}

In [28]:
from sklearn.model_selection import GridSearchCV


scores = []

for model_name, model_params in models.items():
    gcv = GridSearchCV(model_params['model'],model_params['params'],cv=5,return_train_score=False)
    gcv.fit(X, y)
    scores.append({
        'Model': model_name,
        'Score': gcv.best_score_,
        'Params': gcv.best_params_
    })

df = pd.DataFrame(scores, columns=['Model','Score','Params'])
df

Model     Score                                      Params
0                  SVM  0.973850                  {'C': 10, 'kernel': 'rbf'}
1        Random Forest  0.942702  {'criterion': 'gini', 'n_estimators': 500}
2  Logistic Regression  0.922114             {'C': 1, 'solver': 'liblinear'}
3             Gaussian  0.806928                                          {}
4          Multinomial  0.870350                         {'fit_prior': True}
5        decision_tree  0.805262                    {'criterion': 'entropy'}